### ISSUE TITLE
OS X app: no text on buttons, cannot convert

### ISSUE THREAD

**Issue by zarazum** [bboc/todoist-converter#2]
App starts without text on buttons, see screenshot:

![screesnshot](https://user-images.githubusercontent.com/1675008/56571356-6fca4380-65c5-11e9-9a01-15bfc3932e6c.png)

When I try to convert file, the app gives exception:

![Скриншот 2019-04-23 13 42 16](https://user-images.githubusercontent.com/1675008/56575390-419d3180-65ce-11e9-9095-b3202368eb15.png)

**Comment by zarazum** [comment]
Similar error with **tdconv**:

```
tdconv x.csv --format opml

Traceback (most recent call last):
  File "/usr/local/bin/tdconv", line 9, in <module>
    load_entry_point('todoist-converter==1.0rc1', 'console_scripts', 'tdconv')()
  File "build/bdist.macosx-10.14-intel/egg/tdconv/tdconv.py", line 115, in main
  File "build/bdist.macosx-10.14-intel/egg/tdconv/tdconv.py", line 48, in convert
  File "build/bdist.macosx-10.14-intel/egg/tdconv/opml.py", line 30, in convert
  File "build/bdist.macosx-10.14-intel/egg/tdconv/common.py", line 66, in convert
  File "build/bdist.macosx-10.14-intel/egg/tdconv/note.py", line 24, in __init__
  File "build/bdist.macosx-10.14-intel/egg/tdconv/note.py", line 32, in _extract_content_and_attachment
KeyError: u'file_name'
```

**Comment by bboc** [comment]
@zarazum Thanks, I will investigate this. 

Which OS version are you on? I haven't had the chance to test this on Mojave yet. Also, what version of Python is on your system? (You can run `python --version` to find out.)

**Comment by zarazum** [comment]
macOS Mojave 10.14.4 (18E226)
Python 2.7.10

I also have Python 3.7.1 installed.
